hazelcast:
  cluster-name: task1-cluster

  network:
    port:
      auto-increment: false
      port: 5701
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - 172.27.0.11
          - 172.27.0.12
          - 172.27.0.13

  # Enable CP Subsystem for IAtomicLong with strong consistency
  cp-subsystem:
    cp-member-count: 3
    group-size: 3
    session-time-to-live-seconds: 300
    session-heartbeat-interval-seconds: 5
    missing-cp-member-auto-removal-seconds: 14400
    fail-on-indeterminate-operation-state: false
    persistence-enabled: false
    base-dir: cp-data
    data-load-timeout-seconds: 120

